dist: bionic

env:
  global:
    - IMAGE_NAME=pkskubeflow/metadata:v1.11
    - CODE_TAG=master

arch:
  - arm64

services:
  - docker

before_install:
  - git clone -b ${CODE_TAG} --depth 1 https://github.com/kubeflow/metadata.git

script:
  - rm metadata/Dockerfile
  - cp build-metadata/Dockerfile metadata/
  - cd metadata
  - docker build -t ${IMAGE_NAME} -f frontend/Dockerfile .
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PWD}
  - docker push ${IMAGE_NAME}
